# Form implementation generated from reading ui file 'duman.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_yangin(object):
    def setupUi(self, yangin):
        yangin.setObjectName("yangin")
        yangin.resize(637, 354)
        self.label = QtWidgets.QLabel(parent=yangin)
        self.label.setGeometry(QtCore.QRect(0, 0, 641, 361))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setPixmap(QtGui.QPixmap("images/fire.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(yangin)
        QtCore.QMetaObject.connectSlotsByName(yangin)

    def retranslateUi(self, yangin):
        _translate = QtCore.QCoreApplication.translate
        yangin.setWindowTitle(_translate("yangin", "Dialog"))
