# Form implementation generated from reading ui file 'hirsiz.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_guvenlik(object):
    def setupUi(self, guvenlik):
        guvenlik.setObjectName("guvenlik")
        guvenlik.resize(573, 351)
        self.label = QtWidgets.QLabel(parent=guvenlik)
        self.label.setGeometry(QtCore.QRect(0, 0, 581, 351))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/hirsiz.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(guvenlik)
        QtCore.QMetaObject.connectSlotsByName(guvenlik)

    def retranslateUi(self, guvenlik):
        _translate = QtCore.QCoreApplication.translate
        guvenlik.setWindowTitle(_translate("guvenlik", "Dialog"))
